dataset_config:
  dataset_filepath: "dataset.csv"
  test_folds:
    - fold_1
  validation_folds:
    - fold_2
  exclude_folds:
    - fold_3
  num_workers: 6
  batch_size: 120
  pin_memory: true


optimizer_config:
  optimizer_name: adam
  learning_rate: 0.003
  weight_decay: 0.0005

scheduler_config:
  milestones:
    - 15
    - 30
    - 35
    - 40
  gamma: 0.2

loss_config:
  loss_name: mse

output_config:
  out_folder: out

model_name: 'unet1d'

epochs_num: 3
save_step_size: 1
device: cuda
